import { useState, useEffect } from 'react'
import { supabase } from '../supabase'

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL

// Detect API URL for Codespaces
function getApiUrl() {
  const url = window.location.origin
  if (import.meta.env.VITE_API_URL) {
    return import.meta.env.VITE_API_URL
  }
  if (url.includes('app.github.dev')) {
    return url.replace('-5173.app.github.dev', '-3001.app.github.dev')
  }
  return 'http://localhost:3001'
}

const API_URL = getApiUrl()

export default function Gallery() {
  const [jobs, setJobs] = useState([])
  const [filteredJobs, setFilteredJobs] = useState([])
  const [models, setModels] = useState([])
  const [selectedModel, setSelectedModel] = useState('all')
  const [selectedStatus, setSelectedStatus] = useState('completed')
  const [lightboxJob, setLightboxJob] = useState(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    fetchData()
  }, [])

  useEffect(() => {
    filterJobs()
  }, [jobs, selectedModel, selectedStatus])

  async function fetchData() {
    setLoading(true)

    // Fetch all jobs
    const response = await fetch(`${API_URL}/api/jobs`)
    const jobsData = await response.json()
    setJobs(jobsData || [])

    // Fetch models
    const { data: modelsData } = await supabase.from('models').select('*').order('name')
    setModels(modelsData || [])

    setLoading(false)
  }

  function filterJobs() {
    let filtered = jobs

    // Filter by status
    if (selectedStatus !== 'all') {
      filtered = filtered.filter(job => job.status === selectedStatus)
    }

    // Filter by model
    if (selectedModel !== 'all') {
      filtered = filtered.filter(job => job.model_id === parseInt(selectedModel))
    }

    setFilteredJobs(filtered)
  }

  return (
    <div className="max-w-7xl mx-auto px-4 py-6">
      {/* Filters */}
      <div className="mb-6 flex gap-4 items-center flex-wrap">
        <div>
          <label className="block text-sm font-medium mb-1">Model</label>
          <select
            value={selectedModel}
            onChange={(e) => setSelectedModel(e.target.value)}
            className="px-4 py-2 bg-gray-800 rounded-lg border border-gray-700"
          >
            <option value="all">All Models</option>
            {models.map(model => (
              <option key={model.id} value={model.id}>{model.name}</option>
            ))}
          </select>
        </div>

        <div>
          <label className="block text-sm font-medium mb-1">Status</label>
          <select
            value={selectedStatus}
            onChange={(e) => setSelectedStatus(e.target.value)}
            className="px-4 py-2 bg-gray-800 rounded-lg border border-gray-700"
          >
            <option value="all">All Status</option>
            <option value="completed">Completed</option>
            <option value="processing">Processing</option>
            <option value="queued">Queued</option>
            <option value="failed">Failed</option>
          </select>
        </div>

        <div className="ml-auto">
          <div className="text-sm text-gray-400">
            {filteredJobs.length} image{filteredJobs.length !== 1 ? 's' : ''}
          </div>
        </div>
      </div>

      {/* Gallery Grid */}
      {loading ? (
        <div className="text-center py-12 text-gray-400">Loading...</div>
      ) : filteredJobs.length === 0 ? (
        <div className="text-center py-12 text-gray-400">
          No images found with the selected filters
        </div>
      ) : (
        <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 gap-4">
          {filteredJobs.map(job => (
            <div
              key={job.id}
              onClick={() => setLightboxJob(job)}
              className="relative aspect-square bg-gray-800 rounded-lg overflow-hidden cursor-pointer hover:ring-2 hover:ring-blue-500 transition-all group"
            >
              {job.result_image_url ? (
                <>
                  <img
                    src={job.result_image_url}
                    alt={`Generated by ${job.models?.name}`}
                    className="w-full h-full object-cover"
                  />
                  <div className="absolute inset-0 bg-black/60 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center">
                    <div className="text-center px-2">
                      <div className="text-sm font-semibold">{job.models?.name}</div>
                      <div className="text-xs text-gray-300 mt-1">Click to view details</div>
                    </div>
                  </div>
                </>
              ) : (
                <div className="flex items-center justify-center h-full">
                  <div className="text-xs text-gray-500 text-center px-4">
                    {job.status === 'processing' ? 'Processing...' : 'No image'}
                  </div>
                </div>
              )}
            </div>
          ))}
        </div>
      )}

      {/* Lightbox Modal */}
      {lightboxJob && (
        <div
          className="fixed inset-0 bg-black/90 z-50 flex items-center justify-center p-4"
          onClick={() => setLightboxJob(null)}
        >
          <div
            className="bg-gray-900 rounded-lg max-w-6xl w-full max-h-[90vh] overflow-y-auto"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="p-6">
              {/* Close Button */}
              <button
                onClick={() => setLightboxJob(null)}
                className="float-right text-gray-400 hover:text-white"
              >
                <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>

              <h2 className="text-2xl font-bold mb-4">Generation Details</h2>

              <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
                {/* Generated Image */}
                <div>
                  <h3 className="text-lg font-semibold mb-2">Generated Image</h3>
                  {lightboxJob.result_image_url ? (
                    <img
                      src={lightboxJob.result_image_url}
                      alt="Generated"
                      className="w-full rounded-lg"
                    />
                  ) : (
                    <div className="aspect-square bg-gray-800 rounded-lg flex items-center justify-center">
                      <span className="text-gray-500">No image</span>
                    </div>
                  )}
                </div>

                {/* Metadata */}
                <div className="space-y-4">
                  <div>
                    <h3 className="text-lg font-semibold mb-2">Model</h3>
                    <p className="text-gray-300">{lightboxJob.models?.name}</p>
                  </div>

                  <div>
                    <h3 className="text-lg font-semibold mb-2">Status</h3>
                    <span className={`px-3 py-1 rounded text-sm ${
                      lightboxJob.status === 'completed' ? 'bg-green-500/20 text-green-400' :
                      lightboxJob.status === 'processing' ? 'bg-blue-500/20 text-blue-400' :
                      lightboxJob.status === 'failed' ? 'bg-red-500/20 text-red-400' :
                      'bg-gray-500/20 text-gray-400'
                    }`}>
                      {lightboxJob.status}
                    </span>
                  </div>

                  <div>
                    <h3 className="text-lg font-semibold mb-2">Positive Prompt</h3>
                    <p className="text-sm text-gray-300 bg-gray-800 p-3 rounded">{lightboxJob.prompt_used}</p>
                  </div>

                  <div>
                    <h3 className="text-lg font-semibold mb-2">Negative Prompt</h3>
                    <p className="text-sm text-gray-300 bg-gray-800 p-3 rounded">{lightboxJob.negative_prompt_used}</p>
                  </div>

                  <div>
                    <h3 className="text-lg font-semibold mb-2">Parameters</h3>
                    <div className="bg-gray-800 p-3 rounded text-sm space-y-1">
                      {lightboxJob.parameters && Object.entries(lightboxJob.parameters).map(([key, value]) => (
                        <div key={key} className="flex justify-between">
                          <span className="text-gray-400">{key}:</span>
                          <span className="text-gray-200">{JSON.stringify(value)}</span>
                        </div>
                      ))}
                    </div>
                  </div>

                  <div>
                    <h3 className="text-lg font-semibold mb-2">Timestamps</h3>
                    <div className="text-sm space-y-1">
                      <div className="flex justify-between">
                        <span className="text-gray-400">Created:</span>
                        <span className="text-gray-200">{new Date(lightboxJob.created_at).toLocaleString()}</span>
                      </div>
                      {lightboxJob.completed_at && (
                        <div className="flex justify-between">
                          <span className="text-gray-400">Completed:</span>
                          <span className="text-gray-200">{new Date(lightboxJob.completed_at).toLocaleString()}</span>
                        </div>
                      )}
                    </div>
                  </div>

                  {lightboxJob.result_image_url && (
                    <a
                      href={lightboxJob.result_image_url}
                      download
                      className="block w-full text-center px-4 py-2 bg-blue-600 hover:bg-blue-700 rounded-lg font-semibold"
                    >
                      Download Image
                    </a>
                  )}
                </div>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
